### PR TITLE
[TASK] Update translationapi to 2.0.0

### PR DESCRIPTION
**Pull request by dhuf**

### CODE REVIEW

**Comment by fabarea** [comment]
Any consequence to upgrade to TranslationApi 2.0 - as major bump?

**Comment by dhuf** [comment]
@fabarea only the v8 support for the translation API

**Comment by fabarea** [comment]
I let Jonas merge here since he would better know the possible side effects with existing setups.

**Comment by dhuf** [comment]
Thanks @fabarea I'll wait for @jrenggli then. Best and hope to see you soon

**Comment by dhuf** [comment]
@jrenggli any news on this ?

**Comment by jrenggli** [comment]
Hi @dhuf. Thanks for your PR. The change looks basically good to me. The new major version of EXT:translationapi was justified by complete rework of the routing schema. This part is not used in EXT:handlebars.

Unfortunately there are 3 commits for 2 changed lines of code in your PR. Could you please squash them?

**Pull request closed without merging**
